[package]
name = "tfhe-aes"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "1.1.3", features = ["integer", "noise-asserts", "nightly-avx512"] }
clap = { version = "4.1", features = ["derive"] }
rayon = "1.10.0"
aes = "0.8"
rand = { version = "0.9.0", optional = true }
hex = "0.4.3"

[features]
default = ["parallel_aes"]
rand_args = ["dep:rand"]
parallel_aes = []